In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

data = np.loadtxt('data-pp6.txt')
xvals = data[:,0]
yvals = data[:,1]
err = data[:,2]

theoryx = np.linspace(xvals[0],xvals[-1],len(xvals))

def theory(x,a, omega, tau):
    return a*np.cos(omega*x)*np.exp(-x/tau)

plt.errorbar(xvals,yvals,marker='s', yerr=err, linestyle='None', label = 'Data')
popt, pcov = curve_fit(theory, xvals, yvals, sigma=err, p0=(100,100,100))
plt.plot(theoryx, theory(theoryx,*popt), label="Fitted Curve", c='r')
plt.xlabel("idk")
plt.ylabel("idk")
plt.title("something's fit")
plt.legend()
plt.show()
print(popt)

<Figure size 640x480 with 1 Axes>

[1.78704999e+01 1.09294753e+02 4.99438541e-02]


In [8]:
def lapplace(C):
    Cp = np.copy(C)
    dx = 0.1 
    k = 1/dx**2
    h = k
    
    
    Cp = k*(np.roll(Cp,axis=2,shift=-1) + np.roll(Cp,axis=2,shift=1) - 2*Cp) + \
         k*(np.roll(Cp,axis=1,shift=-1) + np.roll(Cp,axis=1,shift=1) - 2*Cp) + \
         k*(np.roll(Cp,axis=0,shift=-1) + np.roll(Cp,axis=0,shift=1) - 2*Cp)
    """
    Cp[1:-1, 1:-1, 1:-1] = (k* (C[0:-2, 1:-1, 1:-1] + C[2:, 1:-1, 1:-1]-2 * C[1:-1, 1:-1, 1:-1])) 
    + (k * (C[1:-1, 0:-2, 1:-1] + C[1:-1, 2:, 1:-1]-2 * C[1:-1, 1:-1, 1:-1])) 
    + (k * (C[1:-1, 1:-1, 0:-2] + C[1:-1, 1:-1, 2:]-2 * C[1:-1, 1:-1, 1:-1]))
    Cp = (k* (C[0:-2, 1:-1, 1:-1] + C[2:, 1:-1, 1:-1]-2 * C[1:-1, 1:-1, 1:-1])) 
    + (k * (C[1:-1, 0:-2, 1:-1] + C[1:-1, 2:, 1:-1]-2 * C[1:-1, 1:-1, 1:-1])) 
    + (k * (C[1:-1, 1:-1, 0:-2] + C[1:-1, 1:-1, 2:]-2 * C[1:-1, 1:-1, 1:-1]))"""
    
    Cp[:,0] = 0
    Cp[:,-1] = 0
    Cp[:,:,-1] = 0
    Cp[:,:,0] = 0
    
    return Cp


In [9]:
import numpy as np
test = np.array([[[1,2,3],[3,4,5],[3,4,5]],[[42,55,65],[5,6,7],[3,4,5]],[[4,5,6],[5,6,7],[3,4,5]]])
test1 = lapplace(test)
print(test1)

#print(test[0:-2, 1:-1, 1:-1])
#print(test[2:, 1:-1, 1:-1])

[[[   0.    0.    0.]
  [   0.  200.    0.]
  [   0.    0.    0.]]

 [[   0.    0.    0.]
  [   0. 4500.    0.]
  [   0.    0.    0.]]

 [[   0.    0.    0.]
  [   0. -500.    0.]
  [   0.    0.    0.]]]


In [ ]:
Cp[1:-1, 1:-1, 1:-1] = k*(np.roll(Cp[1:-1, 1:-1, 1:-1],axis=2,shift=-1) + 
           np.roll(Cp[1:-1, 1:-1, 1:-1],axis=2,shift=1) - 
           2*Cp[1:-1, 1:-1, 1:-1])+ \
         h*(np.roll(Cp[1:-1, 1:-1, 1:-1],axis=1,shift=-1) + 
           np.roll(Cp[1:-1, 1:-1, 1:-1],axis=1,shift=1) - 
           2*Cp[1:-1, 1:-1, 1:-1]) + \
         k*(np.roll(Cp[1:-1, 1:-1, 1:-1],axis=0,shift=-1) + 
            np.roll(Cp[1:-1, 1:-1, 1:-1],axis=0,shift=1) - 
            2*Cp[1:-1, 1:-1, 1:-1])
    