# Exercise 8

Sept 30, 2019. Due Oct 2, 9am.

Enter the names, and describe the contributions of anybody besides yourself who contributed/collaborated.


# Data Fitting and Plotting

1) Using the command line, copy our trusty sample data file, `examplearray.txt` in from your Exercise 5 directory (or /home2/phys210/Public if you managed to mangle it).

Write a function, `line(x, m, b)` that takes a one-dimensional array, $x$ and parameters $m$ and $b$ and calculates a new one dimensional array $y = m x +b$.


In [1]:
def line(x, m, b):
    return (m*x + b)
    


In [2]:
# test that line() executes and returns the correct variables
import numpy as np
from numpy.testing import assert_equal, assert_almost_equal
xdat9 = np.array([1,2,3,4])
ydat9 = line(xdat9, 3, 1)
assert type(ydat9) == np.ndarray


In [3]:
# test that the values returned by line are correct

Read in the x, y, and yerror columns from the file and place them in three one-dimensional arrays with names x, y, yerror. Print these three arrays out don't worry about formatting, this is just so you can verify that the correct data is in the three arrays, and they are in fact one-dimensional arrays.

In [4]:
x = np.loadtxt('examplearray.txt',usecols=(1))
y = np.loadtxt('examplearray.txt',usecols=(2))
yerror = np.loadtxt('examplearray.txt',usecols=(4))

In [5]:
# test that the three arrays exist
print(x)
print(y)
print(yerror)



[1.24 1.26 1.28 1.3  1.33 1.35]
[3.14 3.89 4.04 4.33 4.67 5.08]
[0.52 0.52 0.53 0.53 0.54 0.54]


In [6]:
# test that the x array has the correct data
assert_almost_equal(x,np2.array([1.24, 1.26, 1.28, 1.30, 1.33, 1.35]),2)

NameError: name 'np2' is not defined

In [ ]:
# test that the y array has the correct data

In [ ]:
# test that the yerror array has the correct data

Use `scipy.optimize.curve_fit()` to fit the data you loaded into x, y, and yerror to the `line()` function you defined earlier. Check the lecture notes (4.1) for an example of using this function. Make sure to include the y errors on the data points. Assume that the errors are absolute errors (pass `absolute_sigma = True` to `curve_fit()`).

Use the variable: `params` to store the array of best fit parameters.

In [ ]:
# set params, using curve_fit
import matplotlib.pyplot as plt
from scipy import optimize

params, pcov = optimize.curve_fit(line,x,y,sigma = yerror, absolute_sigma = True)



In [ ]:
# check that params is an array of two values
assert params.size == 2
assert params.ndim == 1

In [ ]:
# check values

In [ ]:
# check values

Plot the data (including y error bars) along with the linear fit. The data points should be plotted with red diamonds, and the fit with a blue solid line. Do not use %matplotlib notebook !

EVERY PLOT YOU EVER MAKE in your whole life (ok, there are some exceptions) should have x and y axes labels, and for stand-alone plots like this, a title as well (a title is not usually used if the plot will have a caption to describe it). Here the x and y axes labels can just be place holders, like “x values” and “y values” but the title should be something useful for the marker, like: Linear fit of examplearray.txt

In [ ]:
plt.title("Linear fit of examplearray.txt")
plt.xlabel("x values")
plt.ylabel('y values')

plt.errorbar(x,y,yerror, fmt="rD")
plt.plot(x,line(x,params[0],params[1]),'b-')
plt.show()

## Scatter plots and histograms

Create 100 random points drawn from a bivariate normal distribution using `numpy.random.multivariate_normal()` Read up on how to use this function using the inline help (eg: help(np.random.multivariate_normal) ). To use this function, you need to pass it a 2x2 covariance matrix. Use 1 for the diagonals and -0.5 for the off-diagonals. Feel free to explore what happens with other values of the elements. Make the means zero. Have this function place your values in a 2d array called `rvals`.



In [ ]:
mean = np.zeros(2)

cov = np.array([[1,-0.5],[-0.5,1]])

rvals = np.random.multivariate_normal(mean, cov, 100)

In [ ]:
assert rvals.shape==(100,2), "rvals has the wrong shape"

In [ ]:
# check values of rvals
assert rvals[:,0].mean() < 0.2
assert rvals[:,1].mean() < 0.2
assert rvals[:,0].std() > 0.5 and rvals[:,0].std() < 1.5
assert rvals[:,1].std() > 0.5 and rvals[:,1].std() < 1.5

Now make a single figure similar to the one shown. 
![](scatter-fig.png) The upper left subplot is a scatter plot of the x and y values. The upper right subplot is a histogram of the x values, and the lower left subplot is a histogram of the y values.

I used 30 bins for the 100 points in the histograms.

`plt.tight_layout()` may come in handy if labels from one subplot overlap with those of another.

In [ ]:
plt.subplot(2,2,1)
plt.scatter(rvals[:,0], rvals[:,1])
plt.title("Scatter plot")
plt.xlabel("x value")
plt.ylabel('y value')

plt.subplot(2,2,2)
plt.hist(rvals[:,0],30)
plt.title("Histogram of x values")
plt.xlabel("x value")
plt.ylabel('Number of x-values')

plt.subplot(2,2,3)
plt.hist(rvals[:,1],30)
plt.title("Histogram of y values")
plt.xlabel("x value")
plt.ylabel('Number of x-values')

plt.tight_layout()
plt.show()