# Exercise 7
Sept 23, 2019. Due Sept 25, 9am.

Enter the names, and describe the contributions of anybody besides yourself who contributed/collaborated. 

Vihara Jayaweera

## Estimate $\pi$
The mathematician Srinivasa Ramanujan found an infinite series that can be used to generate a numerical approximation of $1 / \pi$:
$$\frac{1}{\pi} = \frac{2\sqrt{2}}{9801} \sum_{k=0}^\infty \frac{(4k)!(1103+26390 k)}{(k!)^4 396^{4k}}$$
 
Write two functions, the first: `calculate_term(k)` should calculate the value of the term for k in the summation (without the prefactor before the summation symbol) and return a single floating-point number. The second function,`estimate_pi()` should use a while loop and the first function to calculate and return an estimate of $\pi$. The while loop should terminate when the most recent term in the sum is smaller than 1e-15 (which is Python notation for $10^{−15}$). Don't multiply by the prefactor until the sum is finished. You may use `math.factorial()` if you wish.

In [40]:
import math

def calculate_term(k):
    val = (math.factorial((4*k))*(1103+(26390*k)))/((math.factorial(k))**4*(396**(4*k)))
    return val

def estimate_pi():
    val = 0
    k = 0
    
    while True:        
        val += calculate_term(k)
        if(calculate_term(k) < 1e-15):
            break            
        k+=1
        
    answ = (9801/(2*math.sqrt(2)*val))
    return answ

In [2]:
# test function can be called and returns a float

In [39]:
assert(calculate_term(0) == 1103)

In [4]:
### check other terms

In [5]:
# test return value

## Monte Carlo I
Many integrals that you will encounter in your physics career do not have analytical solutions. The only way to solve them is using numerical methods. Computing certain integrals, especially with many dimensions, can be very hard and time consuming, even with numerical integration methods. A surprisingly simple but effective method is Monte Carlo integration (https://en.wikipedia.org/wiki/Monte_Carlo_integration). As a very simple example of Monte Carlo integration, you will calculate the area of a unit circle ($A = \pi$) in this exercise. The algorithm works as follows:

You examine a number of points distributed randomly throughout the unit square. For large numbers of points, the ratio of the number of points within the unit circle and the total number of points will approach the ratio of the area of a quadrant of the unit circle and the area of the unit square, i.e., $\pi/4$. This is illustrated in the figure below. Essentially you want the ratio of the red points to the total number of points.
![](monte-carlo-pi.png)
Write a function called `monte_carlo_pi(N)` that will:
1.  create N random points on the unit square, by creating two arrays, x and y, each with N random numbers between 0 and 1.
2. Loop over the N points (using a for loop) to check whether they lie within the circle. 
3. The function should return the ratio of the points found inside the circle to the total number of points examined, multiplied by four.


In [6]:
import random 
import numpy as np

def monte_carlo_pi(N):
    x = np.random.random(N)
    y = np.random.random(N)
    in_c = 0
    t_c = 0
    
    for n in range(0,N):
        if(math.sqrt((x[n])**2 + (y[n])**2) <= 1):
            in_c += 1            
        t_c += 1
    return (in_c/t_c)*4


In [35]:
# test that function can be called successfully
a = monte_carlo_pi(200)

In [8]:
# test return value

In [9]:
# test values returned

# Monte Carlo accuracy
Explore how the accuracy of your `monte_carlo_pi(N)` integration varies with N.  To do this, you will call `monte_carlo_pi(N)` function 100 times for each of the following values of N [10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000]. Then for each N value, calculate the average and standard deviations of your estimates. 

Write a function `accuracy()` that does this work, and returns an array having one row for each N value, and three columns: the first containing the N value, the 2nd should contain the average of the 100 calculations and the 3rd is the standard deviation (ddof=1). This will function may take several seconds to execute. You might want to have it print out something periodically so that you know its still running (perhaps one line per N value). While you are developing and testing this, you may want to omit the largest couple of values of N.

In [31]:
from numpy.testing import assert_equal
def accuracy():
    arr = np.array([10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000])
    store = np.ndarray(shape = (len(arr),3))
    calcs = np.empty(100)
  
    for n in range(0,len(arr)):
        store[n][0] = arr[n]
        
        for m in range(0, len(calcs)):
            val = monte_carlo_pi(arr[n])
            calcs[m] = val
        
        store[n][1] = np.average(calcs)
        store[n][2] = np.std(calcs, ddof = 1)
                            
    return store

[[1.00000000e+01 3.19600000e+00 5.25687621e-01]
 [2.00000000e+01 3.17200000e+00 3.43505400e-01]
 [5.00000000e+01 3.15120000e+00 2.44640656e-01]
 [1.00000000e+02 3.14640000e+00 1.96142187e-01]
 [2.00000000e+02 3.14840000e+00 1.09477363e-01]
 [5.00000000e+02 3.14312000e+00 7.38999159e-02]
 [1.00000000e+03 3.14108000e+00 4.77632376e-02]
 [2.00000000e+03 3.14456000e+00 3.63407888e-02]
 [5.00000000e+03 3.14337600e+00 1.87938799e-02]
 [1.00000000e+04 3.14144400e+00 1.72289533e-02]]


In [11]:
# test function can be called successfully and returns a 2d array
a = accuracy()
assert a.ndim == 2

In [12]:
# test that first column values are correct:

assert_equal(a[:,0], np.array([10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000]) )


In [13]:
# test that values of std dev's are reasonable

In [14]:
# test that averages are reasonable

## Newton's Method II
Rewrite your function `which_root_z4(z0)` from the last assignment to use a `for` loop. Either make use of the `break` keyword, or return to avoid computing additional iterations once you know that the sequence will converge (test this by checking to see if the distance to one of the roots is less than 0.25 - note that this is a different bound from the value of 0.02 used in exercise 6).

The function should return values of 0, 1, 2 or 3 for the roots as before, and again return -1 if the sequence doesn’t converge within the maximum number of steps (100). Again, the total number of steps required (which may be zero) should be returned as the second variable.



In [15]:
import numpy as np

def which_root_z4(z0):    
    roots = np.array([1,1j,-1,-1j])
    
    for i in range(0,101):
        if(i == 0):
            check_r = abs(roots - z0)
            n = np.argmin(check_r)
            if( check_r[n] < 0.02):
                return n, i
        else:
            i+=1
           
        fprime = 4*z0**3
        f = z0**4 - 1        
        z0_1 = z0 - (f/fprime) #guess        
        check_r = abs(roots - z0_1) #check root - guess
        n = np.argmin(check_r) #index of lowest diff

        if(check_r[n] < 0.02 ):
            return n, i

        z0 = z0_1
        
    return -1,100

In [34]:
# check that function exists and can be called correctly, it returns two integers
import numbers
i, n = which_root_z4( -4.0)
assert isinstance(i, numbers.Integral) == True
assert isinstance(n, numbers.Integral) == True


In [17]:
# check that the correct value is converged to:

In [18]:
# some trickier tests

In [19]:
### more trickier tests

In [20]:
# check number of iterations

In [21]:
# check numbers of iterations